version: '3.4'

services:
  tradelens.server:
    image: ${DOCKER_REGISTRY-}tradelensserver
    build:
      context: .
      dockerfile: TradeLens.Server/Dockerfile
    ports:
      - "5000:8081" # Expose the backend on port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development