services:
  tradelens.server:
    image: ${DOCKER_REGISTRY-}tradelensserver
    build:
      context: .
      dockerfile: TradeLens.Server/Dockerfile
    ports:
      - "5000:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TradeLensDb=Host=tradelens.db;Database=TradeLens;Username=tradelens;Password=tradelens
    depends_on:
      - tradelens.db

  tradelens.db:
    image: postgres:15
    environment:
      POSTGRES_USER: tradelens
      POSTGRES_PASSWORD: tradelens
      POSTGRES_DB: TradeLens
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
