export const TRADE_JOURNAL_HEADER = [
   {
      title: 'Id',
      align: 'start',
      sortable: true,
      key: 'id',
   },   {
      title: 'Pair',
      align: 'start',
      sortable: true,
      key: 'pair',
   },
   {
      title: 'Type',
      align: 'start',
      sortable: true,
      key: 'type',
   },
   {
      title: 'Result',
      align: 'start',
      sortable: true,
      key: 'result',
   },
   {
      title: 'Note',
      align: 'start',
      sortable: true,
      key: 'note',
   },
   {
      title: 'Profit',
      align: 'start',
      sortable: true,
      key: 'profit',
   },
   {
      title: 'Entry date',
      align: 'start',
      sortable: true,
      key: 'entryDate',
   },
   {
      title: 'Close date',
      align: 'start',
      sortable: true,
      key: 'closeDate',
   },
   {
      title: 'H4 Pattern',
      align: 'start',
      sortable: true,
      key: 'h4Pattern',
   },
   {
      title: 'H4 Screenshot',
      align: 'start',
      sortable: true,
      key: 'h4Screenshot',
   },
   {
      title: 'Daily Pattern',
      align: 'start',
      sortable: true,
      key: 'dailyPattern',
   },
   {
      title: 'Daily Screenshot',
      align: 'start',
      sortable: true,
      key: 'dailyScreenshot',
   },
   {
      title: 'Weekly Screenshot',
      align: 'start',
      sortable: true,
      key: 'weeklyScreenshot',
   },
   {
      title: 'Weekly Last Candle Close',
      align: 'start',
      sortable: true,
      key: 'weeklyLastCandleClose',
   },
   {
      title: 'Weekly supply and demand',
      align: 'start',
      sortable: true,
      key: 'weeklySupplyAndDemand',
   },
   {
      title: 'Weekly Market structure',
      align: 'start',
      sortable: true,
      key: 'weeklyMarketStructure',
   },
   {
      title: 'Weekly Fibonacci',
      align: 'start',
      sortable: true,
      key: 'weeklyFibonacci',
   },
   {
      title: 'Missed',
      align: 'start',
      sortable: true,
      key: 'missed',
   },
]